version: '3'
services:
    front:
        build: .
        ports:
            - 8080:80
    back:
        build: "../dischat_backend"
        ports:
            - 8081:8081
    db:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ../dischat_database/init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ../dischat_database/data:/var/lib/postgresql/data
            # - data:/var/lib/postgresql/data
    # adminer:
    #     image: adminer
    #     ports:
    #         - 8083:8080

# volume:
#     data: